[package]
name = "language-server"
version = "0.2.0"
edition = "2024"

[dependencies]
tower-lsp = "0.20.0"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
env_logger = "0.11.8"
syn = { version = "2.0.101", features = [
    "full",
    "extra-traits",
    "visit",
    "parsing",
] }

[dev-dependencies]
tokio-test = "0.4"
