blank_issues_enabled: false
contact_links:
  - name: Solana VSCode Extension Documentation
    url: https://github.com/ackee-blockchain/solana-vscode/blob/main/README.md
    about: Please check the documentation before creating an issue
