name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  language-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Build language server
      run: |
        cd language-server
        cargo build --verbose

    - name: Run language server tests
      run: |
        cd language-server
        cargo test --verbose

  extension:
    runs-on: ubuntu-latest
    needs: language-server
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install extension dependencies
      run: |
        cd extension
        npm ci

    - name: Build extension
      run: |
        cd extension
        npm run compile

    - name: Run extension tests
      run: |
        cd extension
        npm run test
